### ISSUE TITLE
MissingMethodException: Method not found: bool .ZInput.GetKey(UnityEngine.KeyCode,bool)

### ISSUE THREAD

**Issue by Adoirsas** [AdvizeGH/Advize_ValheimMods#15]
[Error  : Unity Log] MissingMethodException: Method not found: bool .ZInput.GetKey(UnityEngine.KeyCode,bool)
Stack trace:
Advize_PlantEasily.PlantEasily+HotKeyBarUpdate.Prefix (System.Boolean& __runOriginal) (at <456235b5323f43e38326c2cb36a68c2f>:0)
(wrapper dynamic-method) HotkeyBar.DMD<HotkeyBar::Update>(HotkeyBar)

Only installed PlantEasy

**Comment by Blastshotting** [comment]
Turned out my Steam didn't realize there was an update to Valheim 0.217.38 n-20 until I restarted Steam; this error disappeared after doing that.
